#!/usr/bin/env python3
import argparse
import sys
import utils

# Reads 'echo' input and changes to upper case
plaintext = sys.stdin.read()
text = plaintext.upper()
text = list(text)

ciphers = []

for i in range(0,26):
    utils.dictionary(i)
    ciphers.append(utils.caesar_encrypt(text,i))

print(ciphers)
        
    