#!/usr/bin/env python3
import argparse
import sys
import utils
from collections import Counter

# Reads 'echo' input and changes to upper case
plaintext = sys.stdin.read()
text = plaintext.upper()
text = list(text)

ciphers = []

for i in range(0,26):
    j = 26 - i
    utils.dictionary(j)
    ciphers.append(utils.caesar_encrypt(text,j))

#print(ciphers)
count = 0

for sentence in range(len(ciphers)):
    l = len(ciphers[sentence])
    E = round(ciphers[sentence].count('E') / l, 2)
    T = round(ciphers[sentence].count('T') / l, 2)
    A = round(ciphers[sentence].count('A') / l, 2)
    O = round(ciphers[sentence].count('O') / l, 2)
    I = round(ciphers[sentence].count('I') / l, 2)
    print(ciphers[sentence], 'E: ' + str(E), 'T: ' + str(T), 'A: ' + str(A), 'O: ' + str(O), 'I: ' + str(I))
