#!/usr/bin/env python3
import argparse

plaintext = input()
parser = argparse.ArgumentParser()
parser.add_argument("key", type = int)
args = parser.parse_args()
key = args.key
text = plaintext.upper()
text = list(text)
#print(key)
#print(text)
alphabet = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z']

def caesar_encrypt(text,key):
    cipher = ''
    for i in text:
        if i in alphabet:
            oldindex = alphabet.index(i)
            newindex = (oldindex + key) % len(alphabet)
            newletter = alphabet[newindex]
        else:
            newletter = i
        cipher += newletter
    return cipher


print(caesar_encrypt(text,key))

    
