#!/usr/bin/env python3
import argparse
import sys
import utils

# Reads 'echo' input and changes to upper case
plaintext = sys.stdin.read()
text = plaintext.upper()
text = list(text)

# Reads key argument
parser = argparse.ArgumentParser()
parser.add_argument("key", type = int)
args = parser.parse_args()
key = args.key

# Encrypts message (utils)
print(utils.caesar_encrypt(text,key))

    
